-- ============================================================================
-- FLEET COMMAND: CAMPUS TRANSIT TRACKING SYSTEM
-- PostgreSQL + PostGIS 5-Table High-Performance Cloud Architecture
-- ============================================================================

-- 1. Enable Required Spatial & Identifier Extensions
CREATE EXTENSION IF NOT EXISTS postgis;
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- ============================================================================
-- TABLE 1: fleet_assets
-- Physical transit vehicles (Buses, Shuttles, Logistics Vans)
-- ============================================================================
CREATE TABLE IF NOT EXISTS fleet_assets (
    id VARCHAR(64) PRIMARY KEY DEFAULT uuid_generate_v4()::text,
    asset_tag VARCHAR(50) UNIQUE NOT NULL,      -- e.g., 'GITAM-BUS-01', 'SHUTTLE-A'
    license_plate VARCHAR(30) NOT NULL,
    model VARCHAR(100) NOT NULL,
    capacity INTEGER NOT NULL DEFAULT 40,
    status VARCHAR(30) NOT NULL DEFAULT 'ACTIVE' 
        CHECK (status IN ('ACTIVE', 'MAINTENANCE', 'OUT_OF_SERVICE', 'DECOMMISSIONED')),
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_fleet_assets_tag ON fleet_assets(asset_tag);
CREATE INDEX IF NOT EXISTS idx_fleet_assets_status ON fleet_assets(status);

-- ============================================================================
-- TABLE 2: personnel
-- Authorized drivers, field transit technicians, and dispatch operators
-- ============================================================================
CREATE TABLE IF NOT EXISTS personnel (
    id VARCHAR(64) PRIMARY KEY DEFAULT uuid_generate_v4()::text,
    employee_id VARCHAR(50) UNIQUE NOT NULL,    -- e.g., 'EMP-8832'
    full_name VARCHAR(100) NOT NULL,
    role VARCHAR(50) NOT NULL DEFAULT 'DRIVER' 
        CHECK (role IN ('DRIVER', 'DISPATCHER', 'SUPERVISOR', 'MAINTENANCE_TECH')),
    phone_number VARCHAR(30),
    license_number VARCHAR(50),
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_personnel_emp_id ON personnel(employee_id);
CREATE INDEX IF NOT EXISTS idx_personnel_active ON personnel(is_active);

-- ============================================================================
-- TABLE 3: active_sessions
-- Operational shifts/trips binding a certified driver to an asset
-- ============================================================================
CREATE TABLE IF NOT EXISTS active_sessions (
    id VARCHAR(64) PRIMARY KEY DEFAULT uuid_generate_v4()::text,
    asset_id VARCHAR(64) NOT NULL,
    personnel_id VARCHAR(64) NOT NULL,
    route_id VARCHAR(50) NOT NULL,             -- e.g., 'ROUTE_KRC_NORTH_LOOP'
    status VARCHAR(30) NOT NULL DEFAULT 'IN_PROGRESS' 
        CHECK (status IN ('IN_PROGRESS', 'PAUSED', 'COMPLETED', 'ABORTED')),
    started_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    ended_at TIMESTAMPTZ,
    metadata JSONB DEFAULT '{}'::jsonb,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_active_sessions_status_asset 
    ON active_sessions(asset_id, status) WHERE status = 'IN_PROGRESS';

CREATE INDEX IF NOT EXISTS idx_active_sessions_status_personnel 
    ON active_sessions(personnel_id, status) WHERE status = 'IN_PROGRESS';

-- ============================================================================
-- TABLE 4: telemetry_logs
-- High-frequency spatial GPS logs emitted from on-vehicle hardware/Android
-- ============================================================================
CREATE TABLE IF NOT EXISTS telemetry_logs (
    id BIGSERIAL PRIMARY KEY,
    session_id VARCHAR(64),
    asset_id VARCHAR(64) NOT NULL,
    
    -- Spatial Geometry column: WGS 84 (SRID 4326) Point
    location GEOMETRY(Point, 4326) NOT NULL,
    latitude NUMERIC(10, 7) NOT NULL,
    longitude NUMERIC(10, 7) NOT NULL,
    altitude NUMERIC(7, 2),                    -- Elevation in meters
    speed NUMERIC(6, 2) NOT NULL DEFAULT 0.0,  -- Ground speed in km/h
    heading NUMERIC(5, 2),                     -- Bearing in degrees (0 - 359.99)
    battery_level NUMERIC(4, 1),               -- Device battery percentage (0 - 100%)
    inside_geofence BOOLEAN NOT NULL DEFAULT FALSE,
    
    recorded_at TIMESTAMPTZ NOT NULL,          -- Timestamp generated by on-board GPS clock
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- PostGIS GiST Index for ultra-fast spatial search & geofence queries
CREATE INDEX IF NOT EXISTS idx_telemetry_logs_location 
    ON telemetry_logs USING GIST (location);

-- Composite B-Tree index for temporal asset queries & history replay
CREATE INDEX IF NOT EXISTS idx_telemetry_logs_asset_recorded_at 
    ON telemetry_logs (asset_id, recorded_at DESC);

CREATE INDEX IF NOT EXISTS idx_telemetry_logs_session_id 
    ON telemetry_logs (session_id);

-- ============================================================================
-- TABLE 5: dynamic_geofences
-- Dynamic multi-polygon geofences drawn by dispatch administrators
-- ============================================================================
CREATE TABLE IF NOT EXISTS dynamic_geofences (
    id VARCHAR(64) PRIMARY KEY,
    name VARCHAR(128) NOT NULL,
    color VARCHAR(32) DEFAULT '#00F0FF',
    type VARCHAR(32) DEFAULT 'polygon',
    coordinates JSONB NOT NULL,
    radius_meters NUMERIC DEFAULT 100,
    polygon_geom GEOMETRY(Polygon, 4326),
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- GiST Spatial Index on dynamic polygon geometries
CREATE INDEX IF NOT EXISTS idx_dynamic_geofences_geom 
    ON dynamic_geofences USING GIST (polygon_geom);

-- ============================================================================
-- CRITICAL MATH RULE: HIGH PERFORMANCE SPATIAL CALCULATION
-- PostGIS ST_DWithin with use_spheroid = false (Spherical Spatial Index Scan)
-- ST_Distance is strictly avoided to prevent sequential scan lag.
-- ============================================================================
CREATE OR REPLACE FUNCTION check_campus_geofence(
    p_longitude NUMERIC,
    p_latitude NUMERIC,
    p_center_longitude NUMERIC DEFAULT 83.377472,  -- KRC Hub Longitude
    p_center_latitude NUMERIC DEFAULT 17.782167,   -- KRC Hub Latitude
    p_radius_meters DOUBLE PRECISION DEFAULT 100.0
)
RETURNS BOOLEAN
LANGUAGE sql
IMMUTABLE
AS $$
    SELECT ST_DWithin(
        ST_SetSRID(ST_MakePoint(p_longitude, p_latitude), 4326)::geography,
        ST_SetSRID(ST_MakePoint(p_center_longitude, p_center_latitude), 4326)::geography,
        p_radius_meters,
        false   -- CRITICAL: use_spheroid = false (Spherical indexing, 5x faster than ellipsoid)
    );
$$;
